"use client";

import { FormEvent, useRef, useState } from "react";
import { ArrowDown, ArrowUpRight, Check, ListChecks, Map, Menu, Mountain, Satellite, ShieldCheck, Wind, X } from "lucide-react";

const features = [
  { icon: Map, title: "Your route. Always with you.", short: "Offline maps", text: "Find your line before you leave. Detailed mountain routes and offline maps are being designed to keep the bigger picture close, even beyond the signal.", label: "EXPLORE WITH PERSPECTIVE" },
  { icon: Satellite, title: "Look ahead. Not just up.", short: "Satellite weather", text: "Mountain weather moves fast. We're exploring satellite-connected forecasts to bring changing conditions into your planning, from the trailhead to higher ground.", label: "READ THE CONDITIONS" },
  { icon: ListChecks, title: "Confidence starts at basecamp.", short: "Prep checklists", text: "From layers to the little essentials. Build a thoughtful packing list, track your preparation, and give every adventure the attention it deserves.", label: "MAKE READY YOUR RITUAL" },
  { icon: ShieldCheck, title: "Know when to go. And pause.", short: "Risk awareness", text: "A clearer view of route difficulty, exposure, and changing conditions. Planned risk insights to support your judgment at every stage of the climb.", label: "STAY A STEP AHEAD" },
  { icon: Wind, title: "Higher up. More in tune.", short: "Altitude & oxygen", text: "Put elevation into perspective. Explore altitude, estimated oxygen availability, and mountain conditions as part of a more considered ascent.", label: "UNDERSTAND THE ALTITUDE" },
];

function Logo({ dark = false }: { dark?: boolean }) {
  return <a href="#" className={`logo ${dark ? "logo-dark" : ""}`} aria-label="Alpine Star home"><span className="logo-mark"><Mountain size={27} strokeWidth={1.8} /><span className="logo-star">&#10022;</span></span>Alpine Star<span className="logo-dot">.</span></a>;
}

export default function Home() {
  const dialog = useRef<HTMLDialogElement>(null);
  const [selected, setSelected] = useState(0);
  const [menu, setMenu] = useState(false);
  const [formStatus, setFormStatus] = useState<"idle" | "submitting" | "success" | "error">("idle");
  const current = features[selected];

  const openWaitlist = () => {
    setMenu(false);
    setFormStatus("idle");
    dialog.current?.showModal();
  };

  const submitWaitlist = async (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    setFormStatus("submitting");
    const form = event.currentTarget;
    const payload = Object.fromEntries(new FormData(form).entries());
    try {
      const response = await fetch("/api/waitlist", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) });
      if (!response.ok) throw new Error("Unable to join waitlist");
      form.reset();
      setFormStatus("success");
    } catch {
      setFormStatus("error");
    }
  };

  return <>
    <a className="skip-link" href="#main">Skip to content</a>
    <header className="site-header"><Logo /><nav aria-label="Main navigation" className={menu ? "nav-open" : ""}><a href="#companion" onClick={() => setMenu(false)}>Your companion</a><a href="#why-we-climb" onClick={() => setMenu(false)}>Why we climb</a><button className="nav-cta" onClick={openWaitlist}>Join the waitlist <ArrowUpRight size={15} /></button></nav><button className="menu-toggle" aria-expanded={menu} aria-label={menu ? "Close navigation" : "Open navigation"} onClick={() => setMenu(!menu)}>{menu ? <X /> : <Menu />}</button></header>
    <main id="main">
      <section className="hero"><img className="hero-image" src="/images/hero.webp" alt="Sunlight breaking over dramatic snow-covered alpine summits" fetchPriority="high" /><div className="hero-shade" /><div className="hero-content"><span className="eyebrow hero-eyebrow"><span className="status-dot" /> FOR THE SUMMITS STILL AHEAD</span><h1>A higher calling.<br />A better way up.</h1><p>Big mountains. Clearer decisions.<br />Meet your future companion for every step<br className="desktop-break" /> between the dream and the summit.</p><button className="button button-orange" onClick={openWaitlist}>Join the waitlist <ArrowUpRight size={19} /></button><span className="hero-note">A new perspective on mountaineering. Coming soon.</span></div><div className="hero-bottom"><a href="#companion" className="scroll-link"><span><ArrowDown size={17} /></span> THE JOURNEY STARTS HERE</a><span className="hero-coordinates"><span>45.8328 N / 6.8650 E</span>THE ALPS. ABOVE THE EVERYDAY.</span></div></section>
      <div className="feature-ribbon"><span className="ribbon-lead">LESS UNCERTAINTY.<br /><strong>MORE POSSIBILITY.</strong></span><div><Satellite /><span>Satellite weather</span></div><div><ListChecks /><span>Prep checklists</span></div><div><Map /><span>Offline maps</span></div><div><ShieldCheck /><span>Risk awareness</span></div><div><Wind /><span>Altitude & oxygen</span></div></div>
      <section className="companion-section section-wrap" id="companion"><div className="section-copy"><span className="eyebrow green-eyebrow"><span className="line" /> BUILT FOR WHAT'S ABOVE</span><h2>Big ambitions.<br />Better prepared.</h2><p className="section-intro">The mountain asks a lot of you.<br />Your preparation shouldn't have to.</p><div className="feature-tabs" role="tablist" aria-label="Explore planned app features">{features.map((feature, index) => <button role="tab" tabIndex={selected === index ? 0 : -1} onKeyDown={event => { const next = event.key === "ArrowRight" ? (index + 1) % features.length : event.key === "ArrowLeft" ? (index - 1 + features.length) % features.length : event.key === "Home" ? 0 : event.key === "End" ? features.length - 1 : null; if (next !== null) { event.preventDefault(); setSelected(next); document.getElementById(`feature-tab-${next}`)?.focus(); } }} aria-selected={selected === index} aria-controls="feature-panel" id={`feature-tab-${index}`} key={feature.short} className={selected === index ? "selected" : ""} onClick={() => setSelected(index)}><feature.icon size={16} />{feature.short}</button>)}</div><div id="feature-panel" className="feature-detail" role="tabpanel" aria-labelledby={`feature-tab-${selected}`}><span className="tiny-label">{current.label}</span><h3>{current.title}</h3><p>{current.text}</p></div><button className="text-button" onClick={openWaitlist}>Be part of the ascent <ArrowUpRight size={18} /></button><p className="concept-note">Currently in development. Features shown are our vision for the app.</p></div><figure className="phone-stage"><div className="stage-orbit orbit-one" /><div className="stage-orbit orbit-two" /><span className="stage-label">PREPARE. EXPLORE. ASCEND.</span><img className="phone-art" src="/images/alpine-star-phone.webp" alt="Concept image of the Alpine Star mobile app displaying an alpine route map" loading="lazy" /><figcaption>A GLIMPSE OF WHAT'S AHEAD &middot; CONCEPT PREVIEW</figcaption></figure></section>
      <section className="story-section" id="why-we-climb"><div className="story-image"><img src="/images/expedition.webp" alt="Mountaineers with backpacks and trekking poles ascending a sunlit alpine ridge" loading="lazy" /><span className="image-caption"><span /> FIND YOUR PERSPECTIVE.</span></div><div className="story-copy"><span className="eyebrow green-eyebrow">NOT JUST A DESTINATION</span><h2>Some things<br />you can only<br />find up here.</h2><p>The quiet before the first step. The people on your rope. The moment the world opens up beneath you.</p><p>We believe the best mountain experiences begin long before the climb. With curiosity, respect, and the confidence that comes from being prepared.</p><span className="story-signoff">For the climb. For the connection.<br /><strong>For the way it makes you feel.</strong></span><Mountain className="story-mountain" size={90} strokeWidth={.6} /></div></section>
      <section className="principles section-wrap"><div className="principles-heading"><span className="eyebrow green-eyebrow">AMBITION, MEET AWARENESS</span><h2>Go far. Stay grounded.</h2></div><div className="principle-grid"><article><span className="principle-number">01 /</span><h3>Preparation is freedom.</h3><p>Bring your route, your kit, and your conditions into focus. Leave more room for the experience.</p></article><article><span className="principle-number">02 /</span><h3>Respect the mountain.</h3><p>Conditions change. Great decisions include turning around. Your judgment always leads the way.</p></article><article><span className="principle-number">03 /</span><h3>Find your kind of higher.</h3><p>Your first alpine ascent or a long-held summit dream. Every mountain journey deserves a thoughtful start.</p></article></div></section>
      <section className="final-cta"><div className="cta-contours" aria-hidden="true">{Array.from({ length: 9 }, (_, index) => <span key={index} style={{ width: 220 + index * 75, height: 220 + index * 75 }} />)}</div><span className="eyebrow"><span className="status-dot" /> YOUR NEXT CHAPTER STARTS HERE</span><h2>There's more<br />up there for you.</h2><p>Be first to hear when Alpine Star is ready for the climb.</p><button className="button button-orange" onClick={openWaitlist}>Join the waitlist <ArrowUpRight size={19} /></button><span className="cta-note">A little more prepared. A lot more possibility.</span></section>
    </main>
    <footer><div className="footer-top"><Logo dark /><span>Made for a life looking up.</span><a href="#main">Back to the top <ArrowUpRight size={15} /></a></div><div className="footer-bottom"><span>&copy; {new Date().getFullYear()} Alpine Star. The journey is just beginning.</span><p>App concept. Illustrative routes and conditions. Always use current mountain guidance and your own judgment.</p></div></footer>
    <dialog ref={dialog} aria-labelledby="waitlist-title" aria-describedby="waitlist-description" className="waitlist-dialog" onClick={event => { if (event.target === dialog.current) dialog.current.close(); }}><button className="dialog-close" aria-label="Close waitlist form" onClick={() => dialog.current?.close()}><X size={22} /></button>{formStatus === "success" ? <div className="waitlist-success"><span className="dialog-icon"><Check size={32} /></span><span className="eyebrow green-eyebrow">YOU'RE ON THE LIST</span><h2 id="waitlist-title">The summit<br />starts here.</h2><p id="waitlist-description">Thanks for joining us. We'll keep you posted as Alpine Star gets closer to launch.</p><button className="button button-green" onClick={() => dialog.current?.close()}>Keep exploring</button></div> : <><span className="eyebrow green-eyebrow">THE FIRST STEP STARTS HERE</span><h2 id="waitlist-title">Join the<br />Alpine Star waitlist.</h2><p id="waitlist-description">Tell us a little about your climbing journey. We'll only use these details to shape Alpine Star and keep you informed.</p><form className="waitlist-form" onSubmit={submitWaitlist}><div className="form-grid"><label className="field field-wide"><span>Name</span><input name="name" autoComplete="name" required maxLength={100} placeholder="Your name" /></label><label className="field"><span>Years climbing</span><input name="yearsExperience" type="number" inputMode="numeric" min="0" max="80" required placeholder="4" /></label><label className="field"><span>Age</span><input name="age" type="number" inputMode="numeric" min="1" max="120" required placeholder="32" /></label><label className="field field-wide"><span>City</span><input name="city" autoComplete="address-level2" required maxLength={100} placeholder="Boulder" /></label><label className="field field-wide"><span>Email</span><input name="email" type="email" autoComplete="email" required maxLength={254} placeholder="you@example.com" /></label><label className="field field-wide"><span>Phone number</span><input name="phone" type="tel" autoComplete="tel" required maxLength={30} placeholder="+1 555 123 4567" /></label></div><label className="consent"><input name="consent" type="checkbox" value="yes" required /><span>I agree to receive Alpine Star updates and understand that I can unsubscribe at any time.</span></label><input className="honeypot" name="website" tabIndex={-1} autoComplete="off" aria-hidden="true" /><button className="button button-green form-submit" type="submit" disabled={formStatus === "submitting"}>{formStatus === "submitting" ? "Joining…" : "Join the waitlist"}<ArrowUpRight size={18} /></button>{formStatus === "error" && <p className="form-error" role="alert">We couldn't add you just yet. Please check your details and try again.</p>}</form></>}</dialog>
  </>;
}
